spring:
  application:
    name: market-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:postgresql://localhost:5432/market_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

app:
  exchangerate:
    api-key: ${EXCHANGERATE_API_KEY}
    base-url: https://v6.exchangerate-api.com/v6
    base-currency: PLN

server:
  port: 8080