version: '3.8'

services:
  postgres-market:
    image: postgres:16-alpine
    container_name: market-postgres
    environment:
      POSTGRES_DB: market_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  postgres-alert:
    image: postgres:16-alpine
    container_name: alert-postgres
    environment:
      POSTGRES_DB: alert_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  postgres-notify:
    image: postgres:16-alpine
    container_name: notify-postgres
    environment:
      POSTGRES_DB: notify_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: market-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"