spring:
  application:
    name: notify-service
  datasource:
    url: jdbc:postgresql://localhost:5434/notify_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host: smtp.gmail.com
    port: 587
    username: wojciechsuj@gmail.com
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8082

app:
  notification:
    recipient-email: wojciechsuj@gmail.com
    sender-email: wojciechsuj@gmail.com